project_name: mdcode
before:
  hooks:
    - go mod tidy
dist: build/dist
builds:
  - env:
      - CGO_ENABLED=0
    goos: ["darwin", "linux", "windows"]
    goarch: ["amd64", "arm64"]
    ldflags:
      - '-s -w -X {{.ModulePath}}/internal/cmd.version={{.Version}} -X {{.ModulePath}}/internal/cmd.appname={{.ProjectName}}'
source:
  enabled: true
  name_template: "{{ .ProjectName }}_{{ .Version }}_source"

archives:
  - id: bundle
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next+{{.ShortCommit}}{{if .IsGitDirty}}.dirty{{else}}{{end}}"

changelog:
  sort: asc
  abbrev: -1
  filters:
    exclude:
      - "^chore:"
      - "^docs:"
      - "^test:"
